[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/quote/*"
  to = "/quote.html"
  status = 200

[[redirects]]
  from = "/get-started"
  to = "/get-started.html"
  status = 200
